# Generated by Django 5.0.7 on 2024-07-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_publicchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchat',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicchat',
            name='chat_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='publicchat',
            name='chat_path',
            field=models.URLField(default=''),
        ),
    ]
