# Generated by Django 5.0.7 on 2024-07-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_publicchat_owner_alter_publicchat_chat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchat',
            name='description',
            field=models.CharField(default='Public room', max_length=256),
        ),
    ]
