# Generated by Django 5.0.7 on 2024-07-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_remove_publicchat_chat_path_publicchat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchat',
            name='host_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
